@baseurl = http://{{hostname}}:{{port}}/{{prefix}}/{{version}}

###
GET {{baseurl}}/user
  ?page=1
  &pageSize=10
  # &username=test1
  # &role=role1
  # &gender=男
  &sort=username HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{baseurl}}/user/1 HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{baseurl}}/user HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "username": "test25",
  "password": "123456",
  "roles": [{"id": 1}, {"id": 2}] 
}

# "roles": [1,2]  新增时roles，两种数据结构都行

###
PATCH  {{baseurl}}/user/17 HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "username": "test17",
  "password": "1234567890",
  "profile": {
    "photo": "photo17",
    "gender": "女",
    "address": "张江高科"
  }
}

###
DELETE {{baseurl}}/user/16 HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{baseurl}}/user/profile/1 HTTP/1.1
Authorization: Bearer {{token}}
