# Docker Compose file for Docker for Windows
version: '3.7'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306 # 3307 is the port on the host
    environment:
      MYSQL_ROOT_PASSWORD: example