export enum dbConfig {
  DB_TYPE = 'DB_TYPE',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_DATABASE = 'DB_DATABASE',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_SYNC = 'DB_SYNC',
  DB_RETRYDELAY = 'DB_RETRYDELAY',
  DB_RETRYATTEMPTS = 'DB_RETRYATTEMPTS',
  DB_AUTOLOADENTITIES = 'DB_AUTOLOADENTITIES',
  DB_LOGGING = 'DB_LOGGING',
}

export enum appConfig {
  APP_PORT = 'APP_PORT',
  APP_PREFIX = 'APP_PREFIX',
}

export enum logConfig {
  LOG_LEVEL = 'LOG_LEVEL',
  LOG_OPEN = 'LOG_OPEN',
  TIMESTAMP = 'TIMESTAMP',
}

export enum jwtConfig {
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRESIN = 'JWT_EXPIRESIN',
}
